---
title: "frog adjectives"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(here)
library(tidyverse)
library(childesr)
library(RColorBrewer)
library(feather)
library(DT)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)

theme_set(theme_classic(base_size = 14))
```

```{r read-data}
utterances <- read_feather(here("data/frog_english_parsed.feather"))

```

```{r get-adjs}
adj_utts <- utterances %>%
  filter(str_detect(utt_parse, "ADJ"))

adj_utts <- adj_utts %>%
  rowwise() %>%
  mutate(adj_positions = list(which(unlist(str_split(utt_parse, " ")) == "ADJ"))) %>%
  mutate(adjectives = list(unlist(str_split(word_parse, " "))[adj_positions])) %>%
  unnest_longer(adjectives) %>%
  select(-adj_positions)

top_adjs <- adj_utts %>%
  count(adjectives) %>%
  arrange(desc(n))
  
datatable(top_adjs)
```

Top adjectives in Frogs English corpus.

```{r num-adjs}
adj_utts %>%
  group_by(id) %>%
  count() %>%
  ggplot() +
  geom_histogram(aes(n))

```

```{r multi-adj}
num_adjs <- adj_utts %>%
  group_by(id) %>%
  summarise(n_adjs = n())

adj_utts <- adj_utts %>%
  left_join(num_adjs)

adj_utts %>%
  distinct(id, speaker_code, gloss, n_adjs) %>%
  mutate(n_adjs = as.factor(n_adjs)) %>%
  group_by(speaker_code, n_adjs) %>% count() %>%
  ggplot(aes(x = speaker_code, y = n, fill = n_adjs)) +
  geom_bar(position="fill", stat="identity") +
  theme_classic()

datatable(adj_utts %>% 
            filter(n_adjs > 1) %>% 
            distinct(speaker_code, gloss, id) %>%
            select(speaker_code, gloss))

```